default.nix: buildrootBase: Disable format hardening
Nix's toolchains enable some hardening features by default, including
checking format-string security. However, this raises errors when
building GCC in the buildroot due to a bad format-string. Since we
don't really care about this issue, just disable the "format"
hardening feature in the toolchain.

This fixes the following compilation error during one of the GCC stage
builds:

../../../libcpp/expr.cc: In function 'unsigned int cpp_classify_number(cpp_reader*, const cpp_token*, const char**, location_t)':
../../../libcpp/expr.cc:807:35: error: format not a string literal and no format arguments [-Werror=format-security]
  807 |             cpp_warning_with_line (pfile, CPP_W_LONG_LONG, virtual_location,
      |             ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  808 |                                    0, message);
      |                                    ~~~~~~~~~~~
../../../libcpp/expr.cc:810:38: error: format not a string literal and no format arguments [-Werror=format-security]
  810 |             cpp_pedwarning_with_line (pfile, CPP_W_LONG_LONG,
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
  811 |                                       virtual_location, 0, message);
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../libcpp/expr.cc:820:33: error: format not a string literal and no format arguments [-Werror=format-security]
  820 |           cpp_warning_with_line (pfile, CPP_W_SIZE_T_LITERALS,
      |           ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  821 |                                  virtual_location, 0, message);
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../libcpp/macro.cc: In member function 'vaopt_state::update_type vaopt_state::update(const cpp_token*)':
../../../libcpp/macro.cc:185:26: error: format not a string literal and no format arguments [-Werror=format-security]
  185 |             cpp_error_at (m_pfile, CPP_DL_ERROR, token->src_loc,
      |             ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  186 |                           vaopt_paste_error);
      |                           ~~~~~~~~~~~~~~~~~~
../../../libcpp/macro.cc:214:34: error: format not a string literal and no format arguments [-Werror=format-security]
  214 |                     cpp_error_at (m_pfile, CPP_DL_ERROR, token->src_loc,
      |                     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  215 |                                   vaopt_paste_error);
      |                                   ~~~~~~~~~~~~~~~~~~
yes
checking for inttypes.h... ../../../libcpp/macro.cc: In function 'cpp_macro* create_iso_definition(cpp_reader*)':
../../../libcpp/macro.cc:3704:25: error: format not a string literal and no format arguments [-Werror=format-security]
 3704 |               cpp_error (pfile, CPP_DL_ERROR, paste_op_error_msg);
      |               ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../libcpp/macro.cc:3719:25: error: format not a string literal and no format arguments [-Werror=format-security]
 3719 |               cpp_error (pfile, CPP_DL_ERROR, paste_op_error_msg);
      |               ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Brian Kubisiak <brian@kubisiak.com>